### ISSUE TITLE
Class attributes truncated names

### ISSUE THREAD

**Issue by koliyo** [abarker/strip-hints#1]
Annotated class attributes get names truncated in comment. Example
```python
class Foo(object):
  bar: str
```

gives

```python
class Foo(object):
  #ar: str
```

Preferably I would like to see

```python
class Foo(object):
  # bar: str
```

**Comment by abarker** [comment]
Chopping off the first character of the variable name doesn't look great, but the choice was made in order to keep the character counts of the original and stripped files the same (so that any Python error messages on the stripped file match the line and character of the original file).  

The code is on line 212 of `strip_hints_main.py`:
```python
t.string = "#" + t.string[1:]
```

It can be changed to this
```python
t.string = "# " + t.string
```
to get the result you would prefer.  This could possibly be made a command-line option.

**Comment by koliyo** [comment]
Ok, I see, by design. Mentioning this in the README would be helpful. Adding command line flag would be even better :)
