### ISSUE TITLE
-o outfile and --help

### ISSUE THREAD

**Issue by jayvdb** [abarker/strip-hints#11]
It would be nice if this tool had a `--help`, and what I was looking for was a `-o outfile` option

**Comment by abarker** [comment]
As far as argument processing, the program should use `argparse`, but it wasn't originally written that way.  That would automatically provide the `--help` command.  An `--outfile` option would also be useful and wouldn't be too hard to add.

I'd be open to PRs for either of these, but as far as maintenance I'm mostly just fixing correctness bugs if they occur.  Redirection works OK for me on output files.

I'm not sure that many people use this application anymore, since one of its main use cases was for Python 2 compatible code.   I'm curious if you have another, more current use-case for the program.

**Comment by ntjess** [comment]
In my case, some of my typing hints are becoming fairly bloated which makes it harder to read function signatures naturally. This repo is one of the search results in my workflow to create pyi files and remove the initial hints

**Comment by abarker** [comment]
I've added both an `--outfile` and `--inplace` option, as well as a `--help` option, in the current version at GH. I'll push it to pypi after a few more tests.

**Comment by abarker** [comment]
Version 0.1.10 with the new options is now up at PyPI.

**Comment by jayvdb** [comment]
Lovely.
