### ISSUE TITLE
Import Error with strip_on_import

### ISSUE THREAD

**Issue by PaulSchweizer** [abarker/strip-hints#6]
When using "strip_on_import", I get subsequent import errors (Py2.7). 

To reproduce, you can use the built-in xml module as an example, but it should be the same for any module:

```python
import strip_hints

strip_hints.strip_on_import("/usr/lib64/python2.7/xml/parsers/__init__.py") # Replace with your location

from xml import parsers
```

The result:

```python
ImportError: cannot import name parsers
```

It's not an issue with the actual stripping, but with the "on_import" part.

**Comment by abarker** [comment]
The import hooks were not handling the dotted imports correctly.  I've pushed a new version with some fixes.  With Python 3 the `py3_also` flag to `strip_on_import` must be false.

**Comment by PaulSchweizer** [comment]
Nice, thanks for the quick fix @abarker, I gave it a quick test and it seems to work now. 
Just for completeness sake, here's an example of how I previously worked around this: https://github.com/PaulSchweizer/ascii-canvas/blob/master/ascii_canvas/__init__.py#L8

**Comment by abarker** [comment]
Just a note that stripping on import does not work for Python 3.6, and may or may not work for earlier versions of Python 3.  The code has only been tested for 2.7 and 3.6, but for 3.6 I get `'StripHintsImporter' object has no attribute 'find_spec'` errors.

Python 3 import hooks should really use `importlib` rather than the legacy, deprecated `imp` module that is currently used for Python 2.  It should also be much simpler to implement, but it hasn't currently been done.

**Comment by abarker** [comment]
Update: I went ahead and pushed a version to GitHub that uses `importlib` for Python 3 strip-on-imports.

**Comment by PaulSchweizer** [comment]
Thanks @abarker for the great work, I'm using it as intended now, take a look here: https://github.com/PaulSchweizer/ascii-canvas/blob/master/ascii_canvas/__init__.py
