### ISSUE TITLE
There should be an option to strip hints from a source code string

### ISSUE THREAD

**Issue by Ark-kun** [abarker/strip-hints#8]
Currently, the library only works with files which is rather unusual.

**Comment by abarker** [comment]
That's because in Python 2 the library function `tokenize.generate_tokens(readline)` takes an argument that implements the interface of the `readline()` method of built-in file objects.  It would be possible to use `StringIO` on string arguments to get the same effect, but when I wrote the module I didn't really consider that as a common use case.  Due to changes in strings and in the tokenize module between Python 2 and Python 3 it can be tricky to ensure that the program works in both cases.

Do you have a use case for stripping type hints from strings?

**Comment by Ark-kun** [comment]
>That's because in Python 2 the library function tokenize.generate_tokens(readline) takes an argument that implements the interface of the readline() method of built-in file objects. It would be possible to use StringIO on string arguments to get the same effect, but when I wrote the module I didn't really consider that as a common use case. Due to changes in strings and in the tokenize module between Python 2 and Python 3 it can be tricky to ensure that the program works in both cases.

It would be great to have similar low-level interface to `generate_tokens` - the ability to pass any string iterable - a list or a generator or readline.

> Do you have a use case for stripping type hints from strings?

Kubeflow Pipelines has a way to turn a python function into component. The process relies on function parameter annotations and involves copying the source code text of a function. No global imports are copied. The problem is that the function definition becomes invalid due to all annotation types not being imported. Stripping the annotations from the topmost function solves the issue.
https://github.com/kubeflow/pipelines/blob/master/samples/tutorials/Data%20passing%20in%20python%20components.ipynb
https://github.com/kubeflow/pipelines/blob/24d77ed4b01356615732791a2ef706fbe7baa643/sdk/python/kfp/components/_python_op.py#L194

**Comment by abarker** [comment]
I added a new function `strip_string_to_string` in the most recent version pushed to GitHub (it's not on PyPI yet).

**Comment by Ark-kun** [comment]
> I added a new function `strip_string_to_string` in the most recent version pushed to GitHub (it's not on PyPI yet). The interface is the same as `strip_file_to_string` except it takes a code string.

Thank you!
